import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import { Space_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { Switch } from '@nextui-org/react';
import Slider from '@/components/ui/Slider';
// import { MoonIcon } from './MoonIcon';
// import { SunIcon } from './SunIcon';
import ThemeSwitch from '@/components/ThemeSwitch';
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <header>
            <ThemeSwitch />
          </header>

          <div className="">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
